module.exports = {
  authenticateRoutes: {
    path: [
      { url: "/sign-up", method: "POST" },
      { url: "/login", method: "POST" },
      { url: "/otp", method: "POST" },
      { url: "/get-sstoken", method: "POST" },
      { url: "/invite-agent", method: "POST" },
      { url: "/get-code", method: "GET" },
      { url: "/get-user-info", method: "POST" },
      { url: "/change-balance", method: "POST" },
      { url: "/show-host-level-info", method: "GET" },
      { url: "/show-sender-level-info", method: "GET" },
      { url: "/gifter-ranking", method: "GET" },
      { url: "/host-ranking", method: "GET" },
      { url: "/login-agency", method: "POST" },
      { url: "/show-sender-levels", method: "GET" },
      { url: "/login-merchant", method: "POST" },
      { url: "/login-merchant-copy", method: "POST" },
      { url: "/login-reseller", method: "POST" },
      { url: "/get-ip", method: "GET" },
      { url: "/login-customer-support", method: "POST" },
      { url: "/zego-stream-webhook", method: "POST" },
      { url: "/zego-webhook", method: "POST" },
      { url: "/custom-games", method: "GET" },
    
      // { url: "/^\/api\/v1\/test\/*/", method: "PATCH" },
    ],
  },
};
